import os
import re

def generate_orca_input(xyz_coords, charge=0, multiplicity=1, functional="B3LYP", basis="def2-SVP", task_type="Opt", num_cores=4):
    """
    Generate an ORCA input string from XYZ coordinates.
    - xyz_coords: string containing XYZ geometry (excluding the first two header lines: num atoms and comment)
    - task_type: 'Opt' for geometry optimization, 'TD-DFT' for absorption spectrum, or both
    """
    # Number of cores for parallel execution
    pal_line = f"%pal nprocs {num_cores} end\n" if num_cores > 1 else ""
    
    # Task configurations
    if task_type.lower() == "opt":
        keywords = f"! {functional} {basis} Opt"
        extra_blocks = ""
    elif task_type.lower() == "td-dft":
        keywords = f"! {functional} {basis}"
        extra_blocks = """
%td
  nroots 10
end
"""
    elif task_type.lower() == "opt_td":
        keywords = f"! {functional} {basis} Opt"
        extra_blocks = """
%td
  nroots 10
end
"""
    else:
        keywords = f"! {functional} {basis} {task_type}"
        extra_blocks = ""

    # Build input contents
    inp = f"# ORCA Calculation generated by DSSC screening pipeline\n"
    inp += pal_line
    inp += f"{keywords}\n"
    inp += f"%maxcore 2000\n" # 2GB per core
    inp += extra_blocks
    inp += f"\n* xyz {charge} {multiplicity}\n"
    inp += xyz_coords.strip() + "\n"
    inp += "*\n"
    
    return inp

def parse_orca_orbitals(stdout_text):
    """
    Parse ORCA output to extract HOMO and LUMO energies in eV.
    """
    homo = None
    lumo = None
    
    # Locate ORBITAL ENERGIES section
    # Format:
    # ORBITAL ENERGIES
    # ----------------
    #  NO   OCC          E(Eh)            E(eV)
    #   0  2.0000      -20.12345        -547.5831
    #  ...
    #  23  2.0000       -0.24567          -6.6850
    #  24  0.0000       -0.12345          -3.3592
    
    lines = stdout_text.split("\n")
    in_orbital_section = False
    orbitals = []
    
    for line in lines:
        if "ORBITAL ENERGIES" in line:
            in_orbital_section = True
            continue
        if in_orbital_section and "------" in line:
            continue
        if in_orbital_section and ("NO " in line or "OCC" in line):
            continue
        if in_orbital_section and not line.strip():
            in_orbital_section = False
            continue
            
        if in_orbital_section:
            # Match: orbital index, occupancy, energy in Eh, energy in eV
            match = re.search(r'^\s*(\d+)\s+([0-2]\.\d+)\s+([-\d\.]+)\s+([-\d\.]+)', line)
            if match:
                orbitals.append((int(match.group(1)), float(match.group(2)), float(match.group(3)), float(match.group(4))))
                
    if orbitals:
        occupied = [o for o in orbitals if o[1] > 0.0]
        unoccupied = [o for o in orbitals if o[1] == 0.0]
        if occupied:
            homo = occupied[-1][3] # energy in eV
        if unoccupied:
            lumo = unoccupied[0][3] # energy in eV
            
    return homo, lumo

def parse_orca_tddft(stdout_text):
    """
    Parse ORCA TD-DFT output to extract:
    - Absorption Maximum (nm)
    - Maximum oscillator strength (f)
    - Corresponding transition state index
    """
    lambda_max = None
    f_max = -1.0
    state_idx = None
    
    # Format of ORCA absorption spectrum table:
    # ABSORPTION SPECTRUM VIA TRANSITION ELECTRIC DIPOLE MOMENTS
    # State   Energy      Wavelength  Oscillator strength
    #         (cm-1)        (nm)              f
    #   1    18532.1        539.6          0.85243
    
    lines = stdout_text.split("\n")
    in_spectrum_section = False
    
    for line in lines:
        if "ABSORPTION SPECTRUM VIA TRANSITION ELECTRIC DIPOLE MOMENTS" in line:
            in_spectrum_section = True
            continue
        if in_spectrum_section and "State " in line:
            continue
        if in_spectrum_section and ("cm-1" in line or "wavelength" in line):
            continue
        if in_spectrum_section and "------" in line:
            continue
        if in_spectrum_section and not line.strip():
            # End of section when empty line is hit after records
            if lambda_max is not None:
                in_spectrum_section = False
            continue
            
        if in_spectrum_section:
            # Match: state index, energy (cm-1), wavelength (nm), oscillator strength (f)
            # Example: "   1      18532.1        539.6      0.85243"
            match = re.search(r'^\s*(\d+)\s+([-\d\.]+)\s+([-\d\.]+)\s+([-\d\.]+)', line)
            if match:
                state = int(match.group(1))
                wavelength = float(match.group(3))
                f_val = float(match.group(4))
                
                # We identify lambda_max as the transition with the highest oscillator strength (most intense absorption)
                if f_val > f_max:
                    f_max = f_val
                    lambda_max = wavelength
                    state_idx = state
                    
    return lambda_max, f_max, state_idx

def create_orca_input_file(opt_xyz_path, dest_inp_path, charge=0, multiplicity=1, functional="B3LYP", basis="def2-SVP", task_type="Opt", num_cores=4):
    """
    Helper function to load an XYZ coordinates file and generate an ORCA input file.
    """
    if not os.path.exists(opt_xyz_path):
        print(f"XYZ file {opt_xyz_path} does not exist.")
        return False
        
    with open(opt_xyz_path, "r") as f:
        lines = f.readlines()
        
    # Extract coordinate lines (skip first two header lines)
    coord_lines = "".join(lines[2:])
    
    inp_content = generate_orca_input(
        coord_lines,
        charge=charge,
        multiplicity=multiplicity,
        functional=functional,
        basis=basis,
        task_type=task_type,
        num_cores=num_cores
    )
    
    os.makedirs(os.path.dirname(dest_inp_path), exist_ok=True)
    with open(dest_inp_path, "w") as f:
        f.write(inp_content)
        
    print(f"Created ORCA input file: {dest_inp_path}")
    return True
